{% set name = "uncommitted" %}
{% set version = "1.8" %}
{% set sha256 = "2dee253029ade921fec3d648ac4bff640a7658436d5fc4feebb84b55c4b435e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install
  preserve_egg_dir: True
  entry_points:
    - uncommitted = uncommitted.command:main

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - uncommitted

  commands:
    - uncommitted --help

about:
  home: https://github.com/brandon-rhodes/uncommitted
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Scan filesystem for changes not committed to version control'
  dev_url: https://github.com/brandon-rhodes/uncommitted

extra:
  recipe-maintainers:
    - proinsias
