travis:
  secure:
    BINSTAR_TOKEN: wD6J1yI+ePILLIqAR9aNNSF6uM14R8nb77r7ic1kl1cAtBfyISDd1MSVMq1tD6XiQUxVrjkCzpUDE8khOAfKARHmUtQF5VTols9lKBynXhEjAinNr+2NrGBJhslIZrS6Kza89P8z4DNHCpTAYBda66yDnEkkDfYWGcuAOq8zGy2eCRusI4AZVEXJmAmsn094JAy0p88mum5mzbN9hlYoOUXQgQY4u96i6KrFqflfVVT3UccMM5zU+mo1cXql/3ypSrJENZzpnQaNuMI8VrfcervXoHMgQXrikLXYfD7HSRo1vnHFdrTsn+2XyA2OP7q4W7O8nGPLxL8tNE1DxZK2R08q/aitkA5IZxRBPjKdm2QoRYVmKl7s/DQrc8OGZHzKGWZ6d2bp0ytyLCX5l4IcZfNBjCgtdTylkTpCghc6aJ9nguL5YSgX/a+kzGxf9x4UVD/PLZbvv+cB86/fw6W5hmlKysFyA2m2IYY10kpJnNVU9gACNrCcctHAYkTJ8pkMFbXy8ZghiJQnA5Pytx3wII2d7/TNLi7YQ+U5nd+7vap3NMP8X1d44OSTEC/HQeiH0nl5n/whgVFZprL2oWVDZKxAYlSBdwQQci0+0fjBTwWYoN4NiCGvxtgfN4D102Zu+ocKIzJFpaDhqcIqxmxmIOAAYCi/0HNu0k4oxphbATE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
